{{- if .Values.workers.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cube.workers.serviceAccountName" . }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.workers.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.workers.serviceAccount.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.workers.serviceAccount.automountServiceAccountToken }}
{{- end }}
